CREATE TABLE IF NOT EXISTS todo (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  title VARCHAR(20) NOT NULL COMMENT 'タイトル',
  is_done BOOL DEFAULT false NOT NULL COMMENT 'ステータス',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '作成日時',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '更新日時',
  PRIMARY KEY (id),
  UNIQUE (title)
) engine=innodb DEFAULT charset=utf8mb4 COMMENT='todo';